apiVersion: org.eclipse.che/v1
kind: CheCluster
metadata:
  name: playground-dev
spec:
  k8s:
    ingressDomain: 'api-pg-dev2-iks-41208c73af8fca213512856c7a09db52-0001.tor01.containers.appdomain.cloud'
    tlsSecretName: ''
  server:
    cheImageTag: ''
    devfileRegistryImage: 'us.icr.io/apihub-cr/che-devfile-registry:latest'
    pluginRegistryImage: 'us.icr.io/apihub-cr/che-plugin-registry:master-2020-09-17T06.11.17Z'
    tlsSupport: true
    selfSignedCert: false
    customCheProperties:
      CHE_WORKSPACE_STORAGE_AVAILABLE__TYPES: "ephemeral"
      CHE_WORKSPACE_STORAGE_PREFERRED__TYPE: "ephemeral"
  database:
    externalDb: false
    chePostgresHostName: ''
    chePostgresPort: ''
    chePostgresUser: ''
    chePostgresPassword: ''
    chePostgresDb: ''
  auth:
    identityProviderImage: ''
    externalIdentityProvider: false
    identityProviderURL: ''
    identityProviderRealm: ''
    identityProviderClientId: ''
  storage:
    pvcStrategy: per-workspace
    pvcClaimSize: 1Gi
    preCreateSubPaths: true
    postgresPVCStorageClassName: 'ibmc-file-gold-gid'
  metrics:
    enable: true
