apiVersion: org.eclipse.che/v1
kind: CheCluster
metadata:
  name: playground-dev-cluster
spec:
  k8s:
    ingressDomain: 'api-hub-dev-d4b80535626182c66d855ee969650fc9-0005.us-south.containers.appdomain.cloud'
    tlsSecretName: ''
  server:
    cheImageTag: ''
    devfileRegistryImage: 'us.icr.io/apihub-cr/che-devfile-registry:master-2020-09-16T12.18.30Z'
    devfileRegistryPullPolicy: 'Always'
    pluginRegistryImage: ''
    tlsSupport: true
    selfSignedCert: false
    customCheProperties:
      CHE_INFRA_KUBERNETES_NAMESPACE_DEFAULT: "sandbox-ws-<username>"
      CHE_WORKSPACE_STORAGE_AVAILABLE__TYPES: "ephemeral"
      CHE_WORKSPACE_STORAGE_PREFERRED__TYPE: "ephemeral"
      CHE_WORKSPACE_DEFAULTMEMORYLIMIT__MB: "2048"
      #CHE_WORKSPACE_DEFAULT__CPU__LIMIT__CORES: "5"
      CHE_WORKSPACE_PROJECTS_STORAGE_DEFAULT_SIZE: "1Gi"

  database:
    externalDb: false
    chePostgresHostName: ''
    chePostgresPort: ''
    chePostgresUser: ''
    chePostgresPassword: ''
    chePostgresDb: ''
  auth:
    identityProviderImage: ''
    externalIdentityProvider: false
    identityProviderURL: ''
    identityProviderRealm: ''
    identityProviderClientId: ''
  storage:
    pvcStrategy: per-workspace
    pvcClaimSize: 1Gi
    preCreateSubPaths: true
    postgresPVCStorageClassName: 'ibmc-file-gold-gid'
  metrics:
    enable: true
